/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.oracle.truffle.secureL;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
