#!/usr/bin/env bash
#
# Copyright (c) 2018, 2019, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# The Universal Permissive License (UPL), Version 1.0
#
# Subject to the condition set forth below, permission is hereby granted to any
# person obtaining a copy of this software, associated documentation and/or
# data (collectively the "Software"), free of charge and under any and all
# copyright rights in the Software, and any and all patent rights owned or
# freely licensable by each licensor hereunder covering either (i) the
# unmodified Software as contributed to or provided by such licensor, or (ii)
# the Larger Works (as defined below), to deal in both
#
# (a) the Software, and
#
# (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
# one is included with the Software each a "Larger Work" to which the Software
# is contributed by such licensors),
#
# without restriction, including without limitation the rights to copy, create
# derivative works of, display, perform, and distribute the Software and make,
# use, sell, offer for sale, import, export, have made, and have sold the
# Software and the Larger Work(s), and to sublicense the foregoing rights on
# either these or other terms.
#
# This license is subject to the following condition:
#
# The above copyright notice and either this complete permission notice or at a
# minimum a reference to the UPL must be included in all copies or substantial
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

function printUsage() {
    echo "Usage:"
    echo "$0 <GraalVM launcher> <launcher args>"
    echo "Example:"
    echo "$0 js example.js"
    exit 0
}

fileName=$(realpath $2)
outputFolder=$(realpath ./output)
toolsFolder=$(dirname "$PWD")
parentFolder=$(dirname "$toolsFolder")
graalFolder="$parentFolder/graal"




#echo "toolsFolder: $toolsFolder"
#echo "parentFolder: $parentFolder"
#echo "graalFolder: $graalFolder"



#
# copy generated java files to graal svm
#
function copyJavaFiles() {
    echo "++++++++++++++++++ Copying generated Java files to graal svm +++++++++++++++++"
    cp "$outputFolder"/*.java "$graalFolder/substratevm/polyt_app/polytaint"
    
}

#
# copy generated json reflection configurations to graal svm
#
function copyJsonFiles() {
    echo "++++++++++++++++++ Copying generated reflection configuration files to graal svm +++++++++++++++++"
    cp "$outputFolder"/*.json "$graalFolder/substratevm/polyt_app/polytaint"
    
}

#
# copy generated SGX files to sgx module
#
function copySGXFiles() {
    echo "++++++++++++++++++ Copying generated C/Cpp/Edl files to sgx module +++++++++++++++++"
    cp "$outputFolder/Proxy_In".* "$graalFolder/sgx/Enclave/graalsgx/polytaint"
    cp "$outputFolder/Proxy_Out".* "$graalFolder/sgx/App/graalsgx/polytaint"
    cp "$outputFolder"/*.edl "$graalFolder/sgx/Enclave/graalsgx/polytaint"
}


#
# clean any previously generated .java files
#
function cleanOld() {
    echo "++++++++++++++++++ Cleaning previously generated files +++++++++++++++++"
    rm -f "$outputFolder"/*.java
    rm -f "$outputFolder"/*.edl
    rm -f "$outputFolder"/*.cpp
    rm -f "$outputFolder"/*.h
    rm -f "$outputFolder"/*.json      
}

function copyFiles() {
    copyJavaFiles
    copyJsonFiles
    copySGXFiles
}

[ -z "$1" ] || [ "$1" == "--help" ] || [ "$1" == "-help" ] && printUsage


cleanOld

LAUNCHER=$1
POLYTAINT=target/polytaint.jar
SECL=securelanguage.jar
shift

GUEST_LANG="js"
IMAGE_TYPE="part"



"$JAVA_HOME/bin/$LAUNCHER" \
    --polyglot \
    --jvm \
    --vm.Dtruffle.class.path.append=$SECL \
    --vm.Dtruffle.class.path.append=$POLYTAINT \
    --polytaint --polytaint.PrimaryGuest=$GUEST_LANG --polytaint.NativeImageKind=$IMAGE_TYPE --polytaint.PrimaryFile=$fileName --polytaint.OutputFolder=$outputFolder\
    "$@"

copyFiles

#copyJavaFiles
#copyJsonFiles
#copySGXFiles
